config/routes.rb
Rails.application.routes.draw do
root to: 'products#index'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :carts,only: [:index]
  resources :users, only: []
  resources :products, only: [:index, :show] do
    resources :carts,only: [:new,:update,:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  def unchecked
    self.where(ckecked_out: false)
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product

  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
has_many :photos, dependent: :destroy
has_many :carts, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :price, presence: true

def all_photos
  self.photos
end

end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  # belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  has_many :carts, dependent: :destroy

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController


  def index
    @carts = Cart.where(user_id:current_user)
  end

  def create
    set_user
    set_product
    @cart = Cart.create!(product_id:set_product,user_id:set_user)
    redirect_to root_path
  end

  def update
    @cart = Cart.(params.id)
  end




end


private
  def set_product
    params[:product_id]
  end

  def set_user
    @user = current_user.id
  end

  def cart_params
    params
      .require(:cart)
      .permit(
        :user_id, :product_id, :amount, :ckecked_out
      )
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    @pictures = @product.all_photos
    @customer = User.new
  end

  def index
    @products=Product.all

    @customer = User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
def cartbutton
button_to "Add" ,product_carts_path(@product.id) , action: "create"
end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper


end

app/views/cart/index.html.erb
<h1>This is in your cart</h1>
<% @carts.each do |item| %>
<%= item.amount %>
<%= item.product.id %>

app/views/carts/index.html.erb
<h1>This is in your cart</h1>
<% @carts.each do |item| %>
<%= item.amount %>
<%= item.product.id %>
<%end%>

app/views/carts/new.html.erb
<%=form_for @product do |f| %>
  <%= @product.name %>






  <%end%>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>


</html>

app/views/products/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Book Store</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span class="glyphicon glyphicon-shopping-cart"></span> 7 - Items<span class="caret"></span></a>
          <ul class="dropdown-menu dropdown-cart" role="menu">
              <li>
                    <span class="item-right">
                        <button class="btn btn-xs btn-danger pull-right">x</button>
                    </span>
                </span>
              </li>
              <li class="divider"></li>
              <li><a class="text-center" href="">View Cart</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-4">
            <div class="card">
                <% @products.each do |product| %>
                <%= image_tag product.photos.first.image, :size => "300x350" %>
                <p><%= link_to product.name, product_path(product.id) %></p>
                <%= product.price %>
                <%= current_user ? (button_to "Add" ,product_carts_path(product.id) , action: "create"):(link_to "buy?", new_user_registration_path) %>
                <br>
                <% end %>
                </a>
                <br />
            </div>
        </div>

                    </a>
                </div>
            </div>
        </div>

    </div>
</div>

app/views/products/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Book Store</a>
    </div>

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span class="glyphicon glyphicon-shopping-cart"></span> 7 - Items<span class="caret"></span></a>
      <ul class="dropdown-menu dropdown-cart" role="menu">
          <li>
                <span class="item-right">
                    <button class="btn btn-xs btn-danger pull-right">x</button>
                </span>
            </span>
          </li>
          <li class="divider"></li>
          <li><a class="text-center" href="">View Cart</a></li>
      </ul>
    </li>
  </ul>
</div><!-- /.navbar-collapse -->


<h1></h1>

<% @product.all_photos.each do |photo| %>
<%= image_tag photo.image, :size => "450x600" %>
<br>
<%= @product.description %>
<%= @product.price %>


<%= current_user ? (cartbutton):(link_to "buy?", new_user_registration_path) %>
<% end %>

app/views/shared/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->

<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Product_Store", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>